#!/usr/bin/env python3
"""Generate controlled 2016-only upper-length-scale diagnostic cards.

The source card is the reviewed v4 wide-support observed configuration.  Each
diagnostic card changes only:

* the active-dataset switches needed to run 2016 alone;
* ``do_combined`` (disabled for the single-dataset bound scan);
* the 2016 resolution-scaled upper length-scale factor; and
* the isolated output directory.

Expected bands, limit toys, and combined-band toys remain disabled.
"""

from __future__ import annotations

import copy
import hashlib
import json
from pathlib import Path
from typing import Any

import yaml


HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
SOURCE = (
    REPO
    / "study_configs"
    / "v4_wide_support_2015full_2016full_2021_10pct_20260803"
    / "config_obsUL90_combined_wide_support_v4_observed_only.yaml"
)
RESULT_ROOT = (
    REPO / "study_results" / "v4p1_2016_ls_upper_optimization_20260804"
)
FACTORS = (8, 10, 12, 15, 20, 25)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def flatten(value: Any, prefix: str = "") -> dict[str, Any]:
    if isinstance(value, dict):
        out: dict[str, Any] = {}
        for key, child in value.items():
            label = f"{prefix}.{key}" if prefix else str(key)
            out.update(flatten(child, label))
        return out
    return {prefix: value}


def main() -> None:
    source = yaml.safe_load(SOURCE.read_text(encoding="utf-8"))
    source_flat = flatten(source)
    manifest: dict[str, Any] = {
        "source_config": str(SOURCE.relative_to(REPO)),
        "source_config_sha256": sha256(SOURCE),
        "factors": list(FACTORS),
        "cards": [],
    }

    allowed = {
        "enable_2015",
        "enable_2021",
        "do_combined",
        "kernel_ls_res_upper_factor_by_dataset.2016",
        "output_dir",
    }
    for factor in FACTORS:
        card = copy.deepcopy(source)
        card["enable_2015"] = False
        card["enable_2016"] = True
        card["enable_2021"] = False
        card["do_combined"] = False
        card["kernel_ls_res_upper_factor_by_dataset"]["2016"] = float(factor)
        output_dir = RESULT_ROOT / f"k{factor:02d}" / "raw_attempt_01"
        card["output_dir"] = str(output_dir)

        path = HERE / f"config_2016full_wide_support_lsupper{factor:02d}.yaml"
        rendered = (
            "# Generated by make_configs.py from the reviewed v4 card.\n"
            "# Observed/asymptotic 2016-only diagnostic; no expected bands or toys.\n"
            + yaml.safe_dump(card, sort_keys=False)
        )
        path.write_text(rendered, encoding="utf-8")

        card_flat = flatten(card)
        differences = sorted(
            key
            for key in set(source_flat) | set(card_flat)
            if source_flat.get(key) != card_flat.get(key)
        )
        required = {"enable_2015", "enable_2021", "do_combined", "output_dir"}
        if not required.issubset(differences) or not set(differences).issubset(allowed):
            raise RuntimeError(
                f"factor {factor}: unexpected source-card differences {differences}"
            )
        if card["make_ul_bands"] or card["do_combined_bands"]:
            raise RuntimeError(f"factor {factor}: a band-production switch is on")
        if int(card["ul_bands_toys"]) != 0 or int(card["combined_bands_n_toys"]) != 0:
            raise RuntimeError(f"factor {factor}: a toy count is nonzero")
        if str(card["cls_mode"]).lower() != "asymptotic":
            raise RuntimeError(f"factor {factor}: CLs mode is not asymptotic")

        manifest["cards"].append(
            {
                "upper_factor": factor,
                "config": str(path.relative_to(REPO)),
                "config_sha256": sha256(path),
                "parsed_differences_from_v4": differences,
                "output_dir": str(output_dir.relative_to(REPO)),
            }
        )

    manifest_path = HERE / "config_manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(FACTORS)} cards and {manifest_path.relative_to(REPO)}")


if __name__ == "__main__":
    main()
